### ISSUE TITLE
Add text share support

### ISSUE THREAD

**Issue by Wrakor** [grishka/NearDrop#110]
Would be awesome to be able to share text from my Android (currently getting a format not supported error), and get a notification on my Mac with the option to Copy to clipboard.

There was a comment suggesting exactly this, but it didn't have any response:
https://github.com/grishka/NearDrop/issues/16#issuecomment-1736403786

Cheers

**Comment by finnmerlett** [comment]
I recently wanted to do this, ran into the error and think it would be super useful! +1

**Comment by gramcraka** [comment]
Currently implemented by #147 and #112

**Comment by PATAPOsha** [comment]
+1
