### ISSUE TITLE
Will this app ever support versions of macos older than 11.0

### ISSUE THREAD

**Issue by ArseniyNoman** [grishka/NearDrop#12]
I have a MacBook pro 13" 2012, and the newest macos version that it supports is 10.15.7. It's very unlikely that it will ever get a software update. So is it even possible to implement support of this version of macos? Because there's a lot of people that have old versions of os, but they would still love to use it. Anyways, thank you for the development of this app, because it's truly amazing!

**Comment by grishka** [comment]
*Probably*. One issue is that the SwiftECC library I use for elliptic curve cryptography relies on CryptoKit, which was only introduced in 11.0.

**Comment by g0ara** [comment]
Same here, my macbook supports macos up to 10.13.6; would be great if NearDrop could run also on older machines, as there are no working alternatives afaik, or are there any??
Thanks for considering and your great work - thumbs up!

**Comment by sukmaraga** [comment]
same here, on my 2012 mac mini on mojave :D

**Comment by johnothwolo** [comment]
The lack of Catalina support honestly caught me off guard.

**Comment by grishka** [comment]
2.0.4 runs on Catalina (10.15). I'm afraid that's as far down as it will go without needing a rewrite in Objective-C. It turns out CryptoKit was introduced in 10.15.
