### ISSUE TITLE
Unable to send files from Mac - NearDrop not showing on Share menu

### ISSUE THREAD

**Issue by mathewparet** [grishka/NearDrop#129]
On my Mac, when I right-click on a file in Finder and click on Share, I don't see NearDrop as an option. I have no problem sending files from my phone to Mac, but since NearDrop doesn't come up in the Share menu, I am unable to send files from Mac.

Chip: M1

**Comment by mathewparet** [comment]
Never mind, found it. 

For those who come here searching for a solution, this is what I did.

System Settings > Privacy & Security > Extensions > Added Extensions.

Scroll down and enabled "Sharing" under NearDrop.

**Comment by osamarao** [comment]
@grishka  Can you add this as an FAQ in the README please?
