### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by ARK215** [grishka/NearDrop#13]
Device: Macbook M1 Pro 2021
OS: Ventura 13.3.1
Description:
Successfully launched on start, then disappeared from the top bar after several minutes.
On relaunch, the icon appears for a moment and disappears.

**Comment by 23ari** [comment]
I've got a similar issue. For me it didn't take minutes for the first crash but it will crash immediately now after starting the app.

Deivce: MacBook Pro Early 2015
OS: Big Sur 11.6

**Comment by JGoldz75** [comment]
I am also experiencing this on an M1 mac on Ventura. But for me, the app won't even start. It just immediately says "NearDrop cannot be opened"

**Comment by grishka** [comment]
> It just immediately says "NearDrop cannot be opened"

You need to open it by right-clicking and selecting "open". This is what Apple calls "security".

**Comment by grishka** [comment]
For those experiencing crashes, can you please look for crash logs in Console.app (in Utilities)?

**Comment by JGoldz75** [comment]
> > It just immediately says "NearDrop cannot be opened"
> 
> You need to open it by right-clicking and selecting "open". This is what Apple calls "security".

Just tried this and still getting the error: The application “NearDrop” can’t be opened.
Here is the error from Console:
Launch failed with Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}

**Comment by grishka** [comment]
> NSWindow drag regions should only be invalidated on the Main Thread!

Ugh, Apple, why are you doing this to me? Who the hell thought that invoking these callbacks on anything but the main thread is a good idea?..

<img width="431" alt="image" src="https://user-images.githubusercontent.com/1478258/232081650-e74de95d-e2eb-4e94-b9ce-332596771bba.png">

**Comment by grishka** [comment]
Fixed in https://github.com/grishka/NearDrop/releases/tag/v1.1.1
