### ISSUE TITLE
Donation options?

### ISSUE THREAD

**Issue by puhitaku** [grishka/NearDrop#145]
Hi, I've greatly benefited from using NearDrop. It works very nicely with my Mac and Pixel 7 Pro.

As far as I see, I found no donation links on your public pages. If you're open to it, adding a donation option could allow fans like me to contribute to your efforts. Understandably, if you prefer not to, that's completely fine. Thanks!

**Comment by grishka** [comment]
Thank you for your appreciation, but I don't take donations for any of my projects for multiple reasons:
- Donations, especially the periodic kind, create a relationship where I implicitly have some responsibilities towards those who donate (we're paying you but you aren't taking your project in our desired direction). I don't want that.
- Taking donations comes with administrative burden I'm not prepared to deal with.
- I'm not seeking any additional income. I have enough savings to last me many years + I also earn some money from my freelance work sometimes + I also participate in Telegram contests.

**Comment by puhitaku** [comment]
Donations shouldn't have that kind of effect, IMO, but I understood your opinion. Keep it up!
