### ISSUE TITLE
Communication error: Transferring files from Samsung to Mac by using Quick Share

### ISSUE THREAD

**Issue by RokGis** [grishka/NearDrop#156]
Transferring from Samsung Galaxy S24 Ultra to MacBook Pro M3 using Quick Share worked fine until this week. Now, anytime I try, the Mac shows this error. However, transferring from Samsung Galaxy Tab S9+ to Mac still works.
<img width="346" alt="image" src="https://github.com/grishka/NearDrop/assets/147180109/354887fd-a747-43d5-9c81-a03e07b6a9ef">

**Comment by MikaSon1** [comment]
Thanks RokGis,

I am experiencing the same issue as you are with my S24U and MacBook Pro M1. They both stopped working and show the same error message. I appreciate you for raising this issue on GitHub, and I want to thank Grishka in advance for fixing it :)

**Comment by kokasaurus** [comment]
Can confirm that this is happening. My S24 Ultra and S24+ are having the same issue, but my other phones do not have this problem.
No idea what caused the issue though.

**Comment by muhep06** [comment]
My Mac doesn't even show up in the list.

**Comment by GalacticSenat** [comment]
same thing for me, always worked till recently (S21 ultra)

**Comment by bartick** [comment]
Just downloaded the app and same thing with me (S20 FE)

**Comment by AgrMayank** [comment]
+1 Seems like something is broken in between after the rebrand :(

**Comment by kohpai** [comment]
Same problem, same notification here

**Comment by KhunHtetzNaing** [comment]
Same on Galaxy 23 and M2 Pro Max Sonoma 14.4.1

**Comment by rickymohk** [comment]
Recently get this error with Pixel 8 and Google Play Services 24.15.58. 
Another phone with Google Play Service 24.15.18 sees no issue.

**Comment by nintendork07** [comment]
it works fine for me on my galaxy s23 & m1 macbook air. when you share, you have to press the quick share icon, it won't just pop up like other devices do, it's available under the "share to devices nearby" section.

**Comment by muhep06** [comment]
In the meantime, it has started to work. I was able to successfully send files from my phone to my Mac. I think Google fixed something.

**Comment by nintendork07** [comment]
this is what shows up for me. it shows up as a regular device now too once you share once

![Screenshot_20240429_024106_Android System](https://github.com/grishka/NearDrop/assets/78343231/8858a625-2b11-4ed8-a356-6233686a04ad)
![Screenshot_20240429_024048_Quick Share](https://github.com/grishka/NearDrop/assets/78343231/bba870d5-9a9f-439a-8c41-984f4df23e97)

**Comment by rickymohk** [comment]
Guys please note that discovery issue is off-topic. This thread is about communication error after sharing.

**Comment by thewookiewon** [comment]
Same for me, get the notification but it disappears instantly on macOS Sonoma 14.4.1 sending from my S24 Ultra

**Comment by dxmahx** [comment]
> In the meantime, it has started to work. I was able to successfully send files from my phone to my Mac. I think Google fixed something.

 Unfortunately it still doesn't work for me

**Comment by jo-benn** [comment]
⚠️ ⚠️ ⚠️ 
PLEASE READ
⚠️ ⚠️ ⚠️ 

If you 
- have the same issue
- no new information to contribute,
please just leave an emoji reaction on this or the initial comment (or just wait patiently).

There is no point in flooding this thread & repository with comments -- it will just annoy the maintainer.

**Comment by freddie-freeloader** [comment]
⚠️ ⚠️ ⚠️ 
PLEASE READ
⚠️ ⚠️ ⚠️ 

If you 
- have the same issue
- no new information to contribute,
please just leave an emoji reaction on this or the initial comment (or just wait patiently).

There is no point in flooding this thread & repository with comments -- it will just annoy the maintainer.

**Comment by MobileSam** [comment]
I did a little bit of digging and was able to find out that the protobuf file `wire_format.proto` seems to be out of date.

`Location_Nearby_Connections_V1Frame` receives a frame type with the `rawValue` of 12 which is not defined in the [definition file](https://chromium.googlesource.com/external/github.com/google/nearby-connections/+/refs/heads/main/sharing/proto/wire_format.proto) I was able to find.

My (really bad not a proper solution) fix is to handle `rawValue` 12 as `unknownFrameType`
After that, everything worked correctly and I received the file on my Mac without any other issues.
If someone can find the updated protobuf files we should be able to fix this issue properly

**Comment by DayDreamingTime** [comment]
> I did a little bit of digging and was able to find out that the protobuf file `wire_format.proto` seems to be out of date.
> 
> `Location_Nearby_Connections_V1Frame` receives a frame type with the `rawValue` of 12 which is not defined in the [definition file](https://chromium.googlesource.com/external/github.com/google/nearby-connections/+/refs/heads/main/sharing/proto/wire_format.proto) I was able to find.
> 
> My (really bad not a proper solution) fix is to handle `rawValue` 12 as `unknownFrameType` After that, everything worked correctly and I received the file on my Mac without any other issues. If someone can find the updated protobuf files we should be able to fix this issue properly

Any chance you could rephrase this in words that a lay person could understand....please.

**Comment by bartick** [comment]
> > I did a little bit of digging and was able to find out that the protobuf file `wire_format.proto` seems to be out of date.
> > `Location_Nearby_Connections_V1Frame` receives a frame type with the `rawValue` of 12 which is not defined in the [definition file](https://chromium.googlesource.com/external/github.com/google/nearby-connections/+/refs/heads/main/sharing/proto/wire_format.proto) I was able to find.
> > My (really bad not a proper solution) fix is to handle `rawValue` 12 as `unknownFrameType` After that, everything worked correctly and I received the file on my Mac without any other issues. If someone can find the updated protobuf files we should be able to fix this issue properly
> 
> Any chance you could rephrase this in words that a lay person could understand....please.

@DayDreamingTime He is just saying that there is a data transfer format that was changed by google. Which is out of date for this code and needs to be updated for fixing this connection issue.

**Comment by DayDreamingTime** [comment]
Which I guess means that that's something the App developer (Grishka) needs to do and not something that I can do.  I am so frustrated about how difficult it is to transfer images from my Samsung phone to my Macbook Pro....I really was enjoying how easy NearDrop was after making myself half crazy with Dex for years.

**Comment by bartick** [comment]
@MobileSam 
Hey Sam thank you for your input. I did some digging and got this protobuf file from google's repo https://github.com/google/nearby/blob/44725985088d0afa3ae6ac0246cce5bf553e5c5c/sharing/proto/wire_format.proto

I hope this is the correct file and would really appreciate if you could fix the protocol buffer issue.

I am not entirely familiar with swift and we are unsure when the library maintainer will get some time to address the issue. I am hoping if someone opens a proper fix PR the maintainer will approve them.

**Comment by MobileSam** [comment]
Hey @bartick 
I'm sorry but this file is also out of date. You can see on [line 195](https://github.com/google/nearby/blob/44725985088d0afa3ae6ac0246cce5bf553e5c5c/sharing/proto/wire_format.proto#L195) that the FrameType enum stops at 7. We would need the one where it goes up to 12 or at least reference 12.

**Comment by Aditya1349** [comment]
Now i am getting same "communication error" problem while transferring from my S21 FE to my MacBook Air. I think it needs an update i guess.

**Comment by DayDreamingTime** [comment]
Thank you!!!!!  It's back and working again.  I am so grateful for all the work that you do.
