### ISSUE TITLE
Cannot send from SamSung S23 to Mac

### ISSUE THREAD

**Issue by dieptran1001** [grishka/NearDrop#160]
Hi,
Recently I've faced this issue. When I send an image file from my Samsung S23 to Mac, there are 2 notices that appear at the same time every time and I cannot download the file as normal. Please check the attached file below
Note: I have reinstalled the app and the issue is still the same. 

https://github.com/grishka/NearDrop/assets/129362628/1896d31a-7780-4f95-9702-d653a2f577c1

**Comment by grishka** [comment]
It seems you have this setting set to "never".
![Снимок экрана 2024-05-15 в 05 42 18](https://github.com/grishka/NearDrop/assets/1478258/ea3efdb0-fcaa-4830-af54-0c7d0bfd1eed)
Or your default setting is to always hide notification content. This setting needs to be set to "when unlocked" or "always" for NearDrop to work.

**Comment by dieptran1001** [comment]
<img width="694" alt="image" src="https://github.com/grishka/NearDrop/assets/129362628/34bcd470-ff37-489b-9c20-cae697b189aa"> I don't believe that is the problem. 
Here in the video, you can see that there is no button to download the file, later on, it shows a communication error notice.
I have tested with Samsung A24, and Samsung S23. They have the same problem.

**Comment by dieptran1001** [comment]
I don't believe that is the problem. 
Here in the video, you can see that there is no button to download the file, also it shows a communication error notice.
My phone and my Mac are connecting to the same wifi network.
I hadn't changed my settings since I downloaded the app, it worked well before. 
I have tested with Samsung A24, and Samsung S23. They have the same problem. 

https://github.com/grishka/NearDrop/assets/129362628/1958d38b-b7b9-45a5-98cb-d15ffeec8389

**Comment by grishka** [comment]
The communication error was fixed in 2.0.3, please update
