### ISSUE TITLE
Change "Nearby Share" to "Quick Share" in Repo Description

### ISSUE THREAD

**Issue by karlhorky** [grishka/NearDrop#172]
First of all, thanks for NearDrop, cool to see some effort at interop on macOS!

In the repo description at the top right of the page on GitHub, the current text does not mention the current name "Quick Share":

> An unofficial Google Nearby Share app for macOS

![Screenshot 2024-07-25 at 17 06 45](https://github.com/user-attachments/assets/861ce0af-e120-45c6-88a1-5393ffb092ca)

[Nearby Share is the old name](https://support.google.com/android/answer/9286773?hl=en#:~:text=This%20feature%20was%20previously%20known%20as%20Nearby%20Share)

It would be nice to change this to "Quick Share" instead, eg:

> An unofficial Google Quick Share app for macOS

## Alternatives Considered

Keep both "Quick Share" and "Nearby Share" (like in the readme)

**Comment by grishka** [comment]
Oh I forgot about this one, done

**Comment by karlhorky** [comment]
Thanks!
