### ISSUE TITLE
App does not launch, it doesn't show any message / prompt, it doesn't show in privacy & security, I already allow installs from identified developers.

### ISSUE THREAD

**Issue by a-eid** [grishka/NearDrop#176]
App does not launch, it doesn't show any message / prompt, it doesn't show in privacy & security, I already allow installs from identified developers.

it simply doesn't show anything.

**Comment by grishka** [comment]
Yes, because it runs in the background. It only shows an icon in the menu bar.
<img width="330" alt="Снимок экрана 2024-08-10 в 23 06 22" src="https://github.com/user-attachments/assets/2bf25db2-4264-433a-b97a-e565f5b90d55">

**Comment by a-eid** [comment]
@grishka my bad sorry.
