### ISSUE TITLE
Quick Share of text from clipboard doesn't work

### ISSUE THREAD

**Issue by PATAPOsha** [grishka/NearDrop#178]
Copy text on Android device and Quick Share doesn't work - "failed" error shows on my Pixel, nothing shows on my Mac.
Files transfer works good.
![Screenshot_20240817-101014](https://github.com/user-attachments/assets/8861e6e9-e0fe-44ca-9e83-02e61a92c90b)

**Comment by grishka** [comment]
Yes, this is intentionally not implemented.

**Comment by PATAPOsha** [comment]
seems there are PRs for this already
https://github.com/grishka/NearDrop/pull/147
https://github.com/grishka/NearDrop/pull/112

@grishka do you have plans to merge them?

**Comment by grishka** [comment]
No, I don't want this feature

**Comment by MitchTalmadge** [comment]
> No, I don't want this feature

Uh...ok. Care to explain why? It's one of the primary features of Quick Share; not including it is like building a third party Reddit app and deciding you don't want to implement the ability to comment on posts.

**Comment by grishka** [comment]
> It's one of the primary features of Quick Share; not including it is like building a third party Reddit app and deciding you don't want to implement the ability to comment on posts.

Umm no? The primary feature is sending files. Sending disembodied text feels like one of those features they hastily duct-taped to the side of the thing last moment before release. I've never used this feature myself outside of trying different things while reverse engineering the protocol.

And as I said, I will implement it by saving text to a file just so all of you stop pestering me about it.

**Comment by isXander** [comment]
First of all, wow, why such hostility for people wanting a Quick Share feature, in the quick share for mac app..??

Why not have such text shared be able to be accepted into the clipboard, instead of a text file, that seems more intuitive.

**Comment by grishka** [comment]
> Why not have such text shared be able to be accepted into the clipboard, instead of a text file, that seems more intuitive.

Because it doesn't visibly end up anywhere when received. This is bad UX.

**Comment by isXander** [comment]
You already have to 'Accept' the transfer in a notification right?

Two buttons:
- 'Accept as .txt'
- 'Accept to clipboard'

**Comment by grishka** [comment]
I am categorically against the clipboard thing.

**Comment by isXander** [comment]
There's no point arguing with you, I would do it myself if I knew swift.

You said yourself you do not use this text sending feaature yourself, so respectfully, what do you actually know about the UX of this feature?

On the android side, you copy something to the clipboard, where you can then quick share it, why exactly is moving the clipboard from one device directly to another bad UX, if you are sharing from the clipboard, is it not reasonable to expect it to end up on the clipboard of the other device?

You also mentioned that Apple does not have this feature in AirDrop, did you ever think as to why this might be? Apple devices already share clipboard automatically, so putting that in AirDrop would be redundent, and confuse users into believing the automatic clipboard sharing feature doesn't exist in the first place. Now *that* is bad UX.

**Comment by grishka** [comment]
> You also mentioned that Apple does not have this feature in AirDrop, did you ever think as to why this might be?

Apple **does** have this feature in AirDrop and it does end up getting saved as a .txt file when you send text to a Mac.

> Apple devices already share clipboard automatically

Only when they're logged into the same Apple ID. If they belong to different people, a file is your only option.

**Comment by grishka** [comment]
> to fail without any details behind the error

Well I do return an "unsupported attachment" error to the other side. Like, they made an actual error code specifically for this case. The problem is that with all those UI redesigns, they stopped showing a detailed error message, now it's just "failed" ¯\\\_(ツ)_/¯
