### ISSUE TITLE
How do I enter the Pin??

### ISSUE THREAD

**Issue by DragoMeteor** [grishka/NearDrop#181]
I tried to send a file to my Mac but every time it would ask for a Pin and there's no way to enter it on my MacBook. I read the FAQ and people's issues and no one's mentioned. this issue. Am I missing something?

**Comment by grishka** [comment]
You don't enter it anywhere. You match it between the devices if you're really paranoid to make sure the end-to-end encryption hasn't been tampered with. It's derived from the encryption key.

**Comment by DragoMeteor** [comment]
What do you mean? I can't change the pin on my phone and if I don't type the pin on the mac I can't confirm the connection and the file fails to send every time...

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
