### ISSUE TITLE
[Feature Request] Shortcuts App Integration

### ISSUE THREAD

**Issue by IlIllIl** [grishka/NearDrop#182]
<img width="352" alt="image" src="https://github.com/user-attachments/assets/8281ecfc-1728-4a70-bf23-1a363e27fe83">
<img width="177" alt="image" src="https://github.com/user-attachments/assets/513aada5-75d5-4b64-8be8-3645e2973a3a">

Hi, I'd like to use this with Shortcuts.app to pop up sharesheets by opening files, and it would be even easier if there's additional support for the Shortcuts App.

**Comment by ndesgranges** [comment]
What are you trying to achieve ? You could use soduto/kde connect (MAC) + Kde connect (Android) for that purpose

**Comment by grishka** [comment]
If you want to send a file from a shortcut, isn't this action ("share [input data] through [application]") exactly what you want?

![Снимок экрана 2024-11-12 в 16 55 05](https://github.com/user-attachments/assets/b74f43a4-dab9-4186-bf9a-e34c47517c9d)

**Comment by grishka** [comment]
This totally works, and I didn't have to do anything to support it
![Снимок экрана 2024-11-12 в 17 00 51](https://github.com/user-attachments/assets/0de59d61-b1d3-4a61-9262-321093231f27)

**Comment by IlIllIl** [comment]
Thank you, the option appeared after re-adding extension from system setting...
