### ISSUE TITLE
How to make it work both ways (Android Pixel 8 to MacBook Air M2 not working for me)?

### ISSUE THREAD

**Issue by raabmar** [grishka/NearDrop#185]
Do I have to do anything special to make it work both ways?

My situation:
MacBook Air M2 → Pixel 8: Works

Pixel 8 → MacBook Air M2 → I don't get any popup or anything where I can add the pin and confirm receiving the files, so it's just trying to send until it aborts the job

I am not sure if I am simply doing something wrong, but I haven't seen a hint in the FAQs.

**Comment by navneetgpro** [comment]
make sure your "do not disturb" is off

**Comment by raabmar** [comment]
That did it! Thanks a lot - I didn't notice that I have "DND" permanently on on my MacBook
