### ISSUE TITLE
Cannot receive files from Android devices.

### ISSUE THREAD

**Issue by soytony** [grishka/NearDrop#186]
Hi, there.
I noticed that it seems unable to receive files from Android devices. The Mac is detected on the quick share screen on Android, however, it takes forever to connect and will end up failed.

The mac is on Sequoia 15.1, and Android devices on A14.

**Comment by jsebasaristi** [comment]
Yes, i install the app and this happens.

**Comment by grishka** [comment]
Please check that NearDrop is allowed to send notifications and that you don't have the "do not disturb" mode active.

**Comment by soytony** [comment]
Thanks!
