### ISSUE TITLE
Using the pin

### ISSUE THREAD

**Issue by Angelk90** [grishka/NearDrop#21]
Hi @grishka , when I share a file it shows me the pin in both devices, but I'm not prompted to enter it.

I don't understand what the pin is for in this case.

**Comment by shmorky** [comment]
hi, the pin is just to check whether youre connecting to the right device. all you need to do to start sharing is selecting accept in the notification on your mac (see image). 
![image](https://user-images.githubusercontent.com/130848689/232230639-ec2db53a-6c58-43a4-bd87-f7363d8f179a.png)

**Comment by grishka** [comment]
The pin is derived from the encryption key just so you know no one is intercepting your connection. You're supposed to match them on both devices, but of course no one does it in practice.
