### ISSUE TITLE
"NearDrop" can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by VinaySC** [grishka/NearDrop#22]
Getting this error, any workarounds?
<img width="268" alt="Screenshot 2023-04-17 at 9 47 11 AM" src="https://user-images.githubusercontent.com/4324345/232376712-03c87831-123b-42f4-9f0e-cee4caea2daf.png">

**Comment by grishka** [comment]
Have you tried reading the readme?
