### ISSUE TITLE
Support sending files

### ISSUE THREAD

**Issue by grishka** [grishka/NearDrop#4]
* Figure out what causes Android to show the "device nearby is sharing" notification. I have a suspicion that it's this: https://developers.google.com/nearby/fast-pair/specifications/introduction
* Test whether choosing "receive" in the "nearby share" tab in Google Files makes the device visible via MDNS without any Bluetooth stuff. If it does, that would be a decent stopgap measure
* The entry point to sending needs to be a share extension so one could just right-click a file in Finder to send it, the same way as AirDrop works
* The share extension needs to present some sort of UI to choose a recipient device, then display the status and the transfer progress
* The protocol part is straightforward: just be the client instead of the server

**Comment by electr1fy0** [comment]
Hey, huge thanks for your work!

Just adding that you could also add drag and drop file/text to Menu Bar icon to trigger the share as an alternative to the Share extension.

**Comment by vdhatterwal** [comment]
Huge, huge thanks ❤️ for this beautiful application.

Eagerly waiting for send support (esp for context menu share extension)

**Comment by vicr123** [comment]
> Test whether choosing "receive" in the "nearby share" tab in Google Files makes the device visible via MDNS without any Bluetooth stuff. If it does, that would be a decent stopgap measure

Just tested it - seems like this is a good way to force it to advertise the MDNS service.

**Comment by LouisCAD** [comment]
Hello @grishka, would you pin this issue so potential contributors can easily spot it?

**Comment by grishka** [comment]
But I don't want any substantial contributions to this project. It's mine.

**Comment by grishka** [comment]
I did somewhat figure out what causes the "device nearby is sharing". It indeed is a BLE advertisement. One example I captured:
```
Service UUID = fe 2c
Service data = fc 12 8e 01 42 00 00 00 00 00 00 00 00 00 e0 2b cb 5e 18 55 60 10 7e 80
```

However, there's a catch — service data is **required** to be present, but macOS's public Bluetooth API is so shittily minimalistic [it doesn't allow that](https://developer.apple.com/documentation/corebluetooth/cbperipheralmanager/1393252-startadvertising?language=objc). I was able to trigger the notification by replaying that BLE advertisement from an Android phone though.

However, there's plenty of private APIs to explore, for example:
https://github.com/w0lfschild/macOS_headers/blob/master/macOS/Frameworks/IOBluetooth/6.0.0d62/IOBluetoothHostController.h#L156

The bytes at the end of the service data, between the 0s and `80`, change every time you open Nearby Share. I'm not sure whether they're completely random or the result of some cryptographic operations.

**Comment by grishka** [comment]
You know you're in for some adventures when you google that one private method you're interested in, and get that class-dumped header as the only result:
![image](https://github.com/grishka/NearDrop/assets/1478258/bb06ed3e-6fdf-4df2-a5ed-cdbf5724b5e4)

**Comment by grishka** [comment]
To sum up my findings: [these low-level private APIs](https://colemancda.github.io/2018/03/25/Hacking-IOBluetooth) no longer work. The methods all simply do nothing and return 0 as of Ventura (I disassembled the IOBluetooth framework to be sure, each of them is literally same 2 instructions). The code on the Google Services side also explicitly checks for that byte sequence (`12 8e 01`) in service data and ignores BLE advertisements that don't contain any service data at all. There's no provision for cases when the service data can't be set — as it is on Apple devices (iOS shares the same Bluetooth API).

This means I can't make a decent sending UX. The user will have to manually activate the MDNS service by going into "Files by Google" and tapping "receive". Even when the Nearby Share visibility is set to "everyone", the MDNS service is still not active unless that pesky BLE advertisement is received.

There might be another way to activate it, like sending a specific broadcast packet over WiFi or something, but I don't have my hopes up. The "Files by Google" workaround will have to do for now, unfortunately.

**Comment by grishka** [comment]
Made some progress:
![Screenshot_20230925-041146](https://github.com/grishka/NearDrop/assets/1478258/5d31e781-2f01-49fa-a9bc-5f4a6c4c07a0)
<img width="428" alt="Снимок экрана 2023-09-25 в 04 15 42" src="https://github.com/grishka/NearDrop/assets/1478258/9716375e-35ce-4fc8-8910-50de0e304b2b">

**Comment by grishka** [comment]
I found a bug in Google Services 🎉

MacOS is rather liberal with the characters it allows in file names. Android is not so much. So if you send a file that contains Android-illegal characters in the name, `=` in my case, the progress bar doesn't even appear on the Android side and the connection eventually times out.

**Comment by ZtheLeader** [comment]
@grishka Hey, On my Macbook M1Max, I can't see NearDrop as an option while sharing a file even though NearDrop is running in background
![image](https://github.com/grishka/NearDrop/assets/26215607/05a26a63-4453-4532-856a-81ce87814df0)

Is there a step that I am missing?
