### ISSUE TITLE
[Feature Request] Add option to hide icon in menu bar

### ISSUE THREAD

**Issue by VityaSchel** [grishka/NearDrop#40]
Hello, Grisha! 
Thank you for developing and publishing to open-source this lovely software and taking time to read this issue.
Please consider the possibility of adding option to hide app's icon in MacOS menu bar, so it doesn't take any space. I would love to run it as background service and hide this icon.
Have a nice day, Viktor.

**Comment by brandoningli** [comment]
A utility like [Hidden Bar](https://apps.apple.com/us/app/hidden-bar/id1452453066) might be of use to you.

**Comment by grishka** [comment]
I just tried dragging it off the menu bar while holding cmd, but it didn't work. I probably need to implement some callback for this but also provide a way to bring the icon back, e.g. by starting the app a second time when it's already running (I saw some apps do it like that).
