### ISSUE TITLE
Neardrop not working on Macbook Air M1

### ISSUE THREAD

**Issue by tobennaUmeh** [grishka/NearDrop#43]
Hello, Grisha!
Thank you for developing and publishing to open-source this delightful software
I've noticed the application does not work on my device(M1 Air), i've tried installing prior versions, however on my android device my laptop is still not showing up as a device on nearby share.

I've attempted to try other android devices, still not working. However it works perfectly on my friends MBP M1, with my android device, leading me to believe it's a MBA M1 issue

**Comment by Sardonyx001** [comment]
Same here... this is the exact error I get:
Failed to receive files from [my name]...
The operation couldn't be completed.
(SwiftProtobuf.BinaryDecodingError error
3.)
<img width="361" alt="Screenshot 0005-06-01 at 23 25 06" src="https://github.com/grishka/NearDrop/assets/41418470/a2a2b961-8501-477e-be01-032a94eb642d">
<img width="361" alt="Screenshot 0005-06-01 at 23 25 06" src="https://github.com/grishka/NearDrop/assets/41418470/3c9f87d8-59fe-47c2-b6f6-e06f632f9545">
<img width="361" alt="Screenshot 0005-06-01 at 23 25 06" src="https://github.com/grishka/NearDrop/assets/41418470/cbaff1a4-6c4a-43bb-9d8a-d994ad8638b6">

**Comment by jcspradley** [comment]
> It's more likely an issue with your home network. I suggest that you check your router settings to look for anything that might block the multicast UDP packets that device discovery relies on, or prevent devices on your local network communicating with each other.

I have the same machine and I'm getting the same exact error. Per your suggestion, I checked my router settings, but as far as I can tell nothing is blocking multicast UDP packets. I don't have issues with any other services over the network.

**Comment by grishka** [comment]
It definitely can't be an issue related to a particular Mac model. As far as apps are concerned, they're all the same (and, fwiw, all varieties of the M1 are essentially the same hardware components just in different quantities).

I was going to ask you to try turning on the hotspot, connecting to it and sharing like that to eliminate any network-configuration-related factors, but apparently Google thought of that too 🙈

![Screenshot_20230602-202925](https://github.com/grishka/NearDrop/assets/1478258/c7a8b04a-4315-46bc-9ab9-f8390a4542b7)

**Comment by tobennaUmeh** [comment]
> I was going to ask you to try turning on the hotspot, connecting to it and sharing like that to eliminate any network-configuration-related factors, but apparently Google thought of that too 🙈


Hello grishka, I just realised the app is working fine, i had an issue yesterday where I was unable to connect to WIFI on my device, and access the internet. i deleted the wifi Service on my network, and added it. 

Whatever it was on my device. Deleting the service and adding it again helped. Thanks for your suggestions, and the app so excited to finally be able to use it🫡👍🏿.

NOTE FOR ANYONE WHO IS FACING THIS ISSUE TRY DELETING THE WIFI SERVICE AND ADDING IT BACK. MIGHT WORK 👍🏿 

![Screenshot_20230602_195933_Google Play services](https://github.com/grishka/NearDrop/assets/94992053/9e8e261e-aeb3-459d-83b0-77084d2f799d)

**Comment by jcspradley** [comment]
This is good news! What do you mean by deleting the wifi service? Do you mean deleting the saved connections on the phone and computer? Or deleting your wifi network and recreating it?

**Comment by tobennaUmeh** [comment]
System settings >> Network >> Delete Service >> Add Service >>
![20230602_210837 (1)](https://github.com/grishka/NearDrop/assets/94992053/72e6f18f-5290-403e-a8ef-c44bd3ad02df)
<img width="722" alt="Screenshot 2023-06-02 at 21 28 57" src="https://github.com/grishka/NearDrop/assets/94992053/5f5d71ad-f263-472e-b8df-160328b08872">

**Comment by tobennaUmeh** [comment]
System settings >> Network >> Delete Service >> Add Service >> WiFi
<img width="720" alt="Screenshot 2023-06-02 at 21 33 03" src="https://github.com/grishka/NearDrop/assets/94992053/fc0a4f31-eacc-4ccf-9139-a87cbdeadd2d">


<img width="654" alt="Screenshot 2023-06-02 at 21 33 38" src="https://github.com/grishka/NearDrop/assets/94992053/5c05d91a-e4d2-47a2-aa03-f808c6a38f4b">
<img width="484" alt="Screenshot 2023-06-02 at 21 34 02" src="https://github.com/grishka/NearDrop/assets/94992053/a2f0fcc2-7423-46dd-a329-ff9e4a5a15cc">

**Comment by jcspradley** [comment]
Thank you for the instructions! It was very thoughtful and appreciated. Unfortunately I still can't get it to work even after deleting it a couple of times.

**Comment by tobennaUmeh** [comment]
Yw, a little sad it didn't work for you. Hopefully it will eventually work.

You could also try a different release version, although i doubt if that would work, but there's no harm in trying

**Comment by vcode1393** [comment]
Same issue getting error messages, Also, app crashed and quit automatically after error message. 


Device: MBA M1
