### ISSUE TITLE
Can't Open NearDrop on my Mac

### ISSUE THREAD

**Issue by gvirus21** [grishka/NearDrop#47]
Problem: I am not able to open the Neardrop app on my MacBook.

- I directly downloaded the latest version from the GitHub releases section and installed it.
- When I try to open it, it just flashes on my screen for half a second and nothing happened.
I don't even see an Icon appear on the notification bar.

Device: I am using a 2021 Macbook Pro 14' with an M1 Pro chip, which is running Mac OS ventura13.3.1 (22E261).

**Comment by yvdjee** [comment]
The app is not verified by apple so you need to go to settings, privacy & security and click "open it anyway"

**Comment by gvirus21** [comment]
> The app is not verified by apple so you need to go to settings, privacy & security and click "open it anyway"


i already did, now i am not getting any warning or anything, it's just doesn't open anymore.

**Comment by greenbeatty** [comment]
I am unable to open release 1.1.1 on my older iMac running Catalina (10.15.7).

I was able to open release 1.1.1 on my 2018 Macbook Pro running Ventura (13.4) but like @gvirus21 , I am experiencing the same issue. It does nothing when I click to open the app. Yes, I did select "open it anyway" in the privacy & security settings.

**Comment by grishka** [comment]
> I am unable to open release 1.1.1 on my older iMac running Catalina (10.15.7).

The minimum supported system version is Big Sur (11).

**Comment by johnothwolo** [comment]
I built it on Catalina, it doesn't work properly. I was going to fix it and propose a separate NearDrop-classic branch, but I don't think it's worth it.

**Comment by grishka** [comment]
I use some APIs that are only available starting with Big Sur, I don't remember which ones. CryptoKit probably?

**Comment by johnothwolo** [comment]
I used [swift-crypto](https://github.com/apple/swift-crypto)

**Comment by grishka** [comment]
2.0.4 runs on Catalina.

**Comment by mtndwells** [comment]
2.0.4 no longer opens on catalina

**Comment by grishka** [comment]
Which error are you getting?
