### ISSUE TITLE
timed out

### ISSUE THREAD

**Issue by tzaqam** [grishka/NearDrop#5]
I tried to send a photo.
1.- Click Share on Android
2.- I selected my mac
3.- In the Android Nearby menu: it only showed the following PIN message: ####

How can i send logs?

![20230413_210555](https://user-images.githubusercontent.com/13905788/231931618-d03fb904-0877-4bd5-8a7e-5414496edf4f.jpg)

**Comment by grishka** [comment]
Please make sure notifications for NearDrop are enabled in system settings and the do not disturb more is off. Version 1.1 I just released kinda fixes this by showing an alert:
<img width="278" alt="Снимок экрана 2023-04-14 в 06 11 36" src="https://user-images.githubusercontent.com/1478258/231932079-874b3072-9f18-4a5c-8049-6e7db13c2d76.png">

**Comment by tzaqam** [comment]
Nice, you right! thank u
