### ISSUE TITLE
Failed to share text

### ISSUE THREAD

**Issue by neobie** [grishka/NearDrop#52]
Failed to share copied text to Macbook.

![image](https://github.com/grishka/NearDrop/assets/4213973/91250a75-9f54-415d-92e2-dfe9ba3c2344)

**Comment by federico-ntr** [comment]
Same thing happens to me when trying to share a link

**Comment by harrisonlingren** [comment]
Same here with links from Android 14 beta --> NearDrop

**Comment by kotprotiv** [comment]
Same with the links, it would be a great feature to implement.

**Comment by nightshifty** [comment]
I think its only working for files right now. 
Would be a great feature :-)
