### ISSUE TITLE
No Notification Received when Using NearDrop

### ISSUE THREAD

**Issue by joaquincorradi** [grishka/NearDrop#55]
**Problem:**
When using the app I encountered an issue where I did not receive any notifications on my MacBook when attempting to share content from my Android phone. Despite following the necessary steps, including enabling notification permissions for NearDrop, activating notification settings on my MacBook, and initiating the sharing process, no notification appeared on my MacBook.

**Steps to Reproduce:**
1. Download and install the NearDrop app on macOS, specifically on an M2 Air.
2. Launch NearDrop on the MacBook.
3. Verify that the notification settings on the MacBook are not in the "Do Not Disturb" (DND) mode.
4. Enable notification permissions for NearDrop to receive all notifications.
5. On an Android phone, initiate the Nearby Share feature.
6. Select a picture or any other content to share.
7. Locate the MacBook as a nearby device to share with.
8. Choose the MacBook from the list of available devices.
9. Observe that the MacBook appears on the Android phone, indicating successful connection.
10. Press the MacBook icon on the Android phone to start sharing.
11. Notice that no notification is displayed on the MacBook.

**Expected Behavior:**
When initiating a share with Nearby Share on my Android phone and selecting my MacBook as the recipient, I expect to receive a notification on my MacBook indicating the incoming shared content.

**Actual Behavior:**
Upon selecting the MacBook as the recipient on the Android phone, no notification appears on the MacBook. Therefore, it is not possible to initiate the sharing process or receive any shared content.

**Environment:**
- macOS version: Ventura 13.4.1
- NearDrop version: 1.1.1
- Android version: OneUI 5.1 on Android 13

**Additional Information:**
I have also tried restarting both the Android phone and the MacBook to no avail. This issue persists consistently, and no error message or indication of the problem is displayed on either device. Furthermore, I have tested the same scenario with another Android device, and the problem persists, indicating that it is not specific to a particular phone.

**Possible Workaround:**
Currently, I have found no workaround for this issue. Any guidance or assistance to resolve this problem would be greatly appreciated.

<img src="https://github.com/grishka/NearDrop/assets/53107439/5cd50e28-7a8a-4540-b73a-2d55c757013a" height="400"></img>

<img src="https://github.com/grishka/NearDrop/assets/53107439/9b8b8525-4a38-449f-930c-2852c1972d7c" height="500"></img>

**Comment by grishka** [comment]
Does the notification also not appear in the notification center above the widgets?

**Comment by joaquincorradi** [comment]
> Does the notification also not appear in the notification center above the widgets?

Thank you for your response and suggestion. I checked the Notification Center on my MacBook as you mentioned, and indeed, I found the notifications from NearDrop there. I apologize for not realizing that the notifications were being directed to the Notification Center instead of appearing as pop-up notifications.

However, my concern is that the notifications do not appear as pop-up notifications on the screen, which makes it easy to miss incoming shares. Is it possible to configure NearDrop to display pop-up notifications as well, in addition to the notifications in the Notification Center?

**Comment by Delocalized-electron** [comment]
Can you try banner in the notification settings?

I have been using banner and i am getting the notifications outside the notification center.

Use banner then restart the Mac, and try again. Hopefully it will work.

**Comment by joaquincorradi** [comment]
Thank you for your assistance. I managed to resolve the notification issue with NearDrop by following your suggestion. After changing the notification settings on my MacBook from "Alert" mode to "Banner" mode and restarting the computer, the pop-up notifications started appearing as expected.
