### ISSUE TITLE
[Feature Add]Progress Bar for incoming transfer

### ISSUE THREAD

**Issue by Delocalized-electron** [grishka/NearDrop#56]
Not an issue, But Feature add,

It would be great if we can see the total progress of the incoming transfer, Like we see in AirDrop.

**Comment by grishka** [comment]
There is already a progress bar if you have your downloads folder in your dock.

**Comment by Delocalized-electron** [comment]
I am talking about the progress bas in notification like there is for air drop

**Comment by grishka** [comment]
AirDrop uses a crapload of private APIs and the deprecated `NSUserNotificationCenter` instead of their own recommendation of `UNUserNotificationCenter`. I tried to replicate the AirDrop notification but it just didn't work, no notification was displayed at all.

**Comment by Delocalized-electron** [comment]
Oh, Ohkay....

I am closing this issue with a workaround.

WORKAROUND: 
Add the Download folder to the Dock or open the download folder in finder to check the progress of the transfer
