### ISSUE TITLE
Internet speed drops when an application is running

### ISSUE THREAD

**Issue by sankovalexandr** [grishka/NearDrop#59]
When the app is running, the internet speed drops from 200 mbps to 40 mbps
Macbook Pro 16 M1 Pro 2021 16 Gb Ventura

**Comment by hiftikha** [comment]
Can you post evidence as to the app being responsible for this change?

**Comment by jesuslopezxing** [comment]
I have been able to reproduce the same issue. With the app running my speed average drops from 400-500 to 100-200.  I have done several attempts.

**Comment by macmanjimmy** [comment]
Same issue, this classifies as a "pattern" 

Neardrop on 116mps off 590mbps
![Screenshot 2023-08-10 at 1 11 34 PM](https://github.com/grishka/NearDrop/assets/93870004/2f6319fe-cd5c-4fd4-94b7-fea59597abde)
![Screenshot 2023-08-10 at 12 58 24 PM](https://github.com/grishka/NearDrop/assets/93870004/df88e0ec-7682-4e1a-86ec-3fe94a916396)

**Comment by grishka** [comment]
IDK, I can't reproduce this problem. I pay for 200 mbit, I get 200 mbit. 
![image](https://github.com/grishka/NearDrop/assets/1478258/f9c4a125-d88c-4a38-8b7f-ce2f6d696273)

NearDrop *just running* shouldn't affect your network speed. The only thing it does is listen on a TCP port for incoming connections (that's fully passive) and advertise a service via mDNS (a.k.a. Bonjour, how Apple calls it). The mDNS part supposedly only responds to broadcast packets that Android devices send when looking for receivers, otherwise doing nothing. But that's implemented by the system, in the daemon called `mDNSResponder`.

**Comment by macmanjimmy** [comment]
> IDK, I can't reproduce this problem. I pay for 200 mbit, I get 200 mbit. ![image](https://user-images.githubusercontent.com/1478258/259873268-f9c4a125-d88c-4a38-8b7f-ce2f6d696273.png)
> 
> NearDrop _just running_ shouldn't affect your network speed. The only thing it does is listen on a TCP port for incoming connections (that's fully passive) and advertise a service via mDNS (a.k.a. Bonjour, how Apple calls it). The mDNS part supposedly only responds to broadcast packets that Android devices send when looking for receivers, otherwise doing nothing. But that's implemented by the system, in the daemon called `mDNSResponder`.

is the app running at the same time? running 13.2.1

**Comment by macmanjimmy** [comment]
> IDK, I can't reproduce this problem. I pay for 200 mbit, I get 200 mbit. ![image](https://user-images.githubusercontent.com/1478258/259873268-f9c4a125-d88c-4a38-8b7f-ce2f6d696273.png)
> 
> NearDrop _just running_ shouldn't affect your network speed. The only thing it does is listen on a TCP port for incoming connections (that's fully passive) and advertise a service via mDNS (a.k.a. Bonjour, how Apple calls it). The mDNS part supposedly only responds to broadcast packets that Android devices send when looking for receivers, otherwise doing nothing. But that's implemented by the system, in the daemon called `mDNSResponder`.

Created a "NEW USER" account no other apps running/ fresh OS same result

Im paying 500mbps, Blessed to get close to 600, but drops like a rock to 116mbs definitely an issue

How about you fly me to Alaska we can meet there and i can show you LOL JK. 

Seriously the app needs work

**Comment by macmanjimmy** [comment]
> I have been able to reproduce the same issue. With the app running my speed average drops from 400-500 to 100-200. I have done several attempts.

You running OCLP what year is your Macbook?

**Comment by jesuslopezxing** [comment]
> OCLP

I don't know what it... I am running 14" M1 Pro 2021

**Comment by macmanjimmy** [comment]
> 

then you not Running it LOL its a bug... developer just needs to recognize and fix it.. we'll see...

I just run and quit when i need it.. app has a serious leak

**Comment by adrianbj** [comment]
I am also seeing a significant speed drop!

**Comment by macmanjimmy** [comment]
awe, everyone except the developer, interesting  LOL have to launch and quit each time I use it..

**Comment by jesuslopezxing** [comment]
Stop treating the developer like a machine that works for you, you are not even paying for anything here. Don't forget that anyone also could open PRs to fix it.

@grishka I think you are not able to reproduce it because of your network speed is already on the limit to the speed during the bug. If you can get somewhere a faster connection maybe you can reproduce it.

**Comment by davystrong** [comment]
I'm experiencing the same issue, however, I'm at the limit of my WiFi range, so it's happening at lower speeds: I get about 32 Mbps, dropping to about 17 when I open NearDrop.

**Comment by macmanjimmy** [comment]
jesuslopezxing : Not treating the Developer like a "Machine".  Its about taking "Ownership" of an issue the developer has a duty to do for its users.

There are numerous reports of issues, and the developer denies it ? he is using a "special" mac we dont have ? LOL 

Its about accountability

**Comment by grishka** [comment]
The license for this app explicitly says that nothing is guaranteed. I'm just putting this stuff out there for everyone to use but I have no obligations whatsoever.

If you want to debug this problem, go for it. Pull requests that fix bugs are welcome too.

**Comment by macmanjimmy** [comment]
Oh, so there is now a bug of sudden... typical

**Comment by grishka** [comment]
Maybe there is, maybe there isn't. We don't know until someone could both reproduce this issue **and** debug it. So far I've only seen people complain with the "fix your crap bro" attitude, with no attempts whatsoever made to pin down the cause.

**Comment by macmanjimmy** [comment]
pushback, again typical

**Comment by grishka** [comment]
Acting entitled as fuck again, typical

**Comment by macmanjimmy** [comment]
whoa.... easy on the language "Comrade", no tears in your "Borscht"

**Comment by macmanjimmy** [comment]
if you're experiencing drops in your bandwidth, just remember to quit after use.

DO NOT USE this app as a "Login item" 
Since the developer (obviously) will not correct this bug, this is the method we have to use...

**Comment by davystrong** [comment]
@macmanjimmy any chance you could try to debug this issue? Set up Xcode, set up the project, try to run it. A tool like Wireshark might help you find what is happening and you could report it here or, better yet, find a solution. It would be very helpful to anyone trying to solve the issue and significantly reduce the time involved, plus it would be an opportunity for you to contribute to a very interesting open source project.

**Comment by grishka** [comment]
> whoa.... easy on the language "Comrade", no tears in your "Borscht"

If you want to bring out my Russian-ness, then I have to say that we have a term in our internet slang for the state of mind you're experiencing — "пукан бомбанул". I encourage you to do an image search for this.

And, @davystrong is right. Go get Xcode and Wireshark and try debugging the thing that makes you so upset. If you manage to fix it, or at least determine the cause, we'll be thankful.

**Comment by unnamed777** [comment]
Probably my issue is related to this one. When the app is running, I observe increased network latency. It's visible everywhere, even when I ping a router:
<details>
  <summary>NearDrop is running, min/avg/max/stddev = 1.407/51.946/251.638/74.576 ms</summary>

```
$ ping -c 20 192.168.1.1
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: icmp_seq=0 ttl=64 time=33.123 ms
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=75.757 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=64 time=122.260 ms
64 bytes from 192.168.1.1: icmp_seq=3 ttl=64 time=163.116 ms
64 bytes from 192.168.1.1: icmp_seq=4 ttl=64 time=207.407 ms
64 bytes from 192.168.1.1: icmp_seq=5 ttl=64 time=1.797 ms
64 bytes from 192.168.1.1: icmp_seq=6 ttl=64 time=1.627 ms
64 bytes from 192.168.1.1: icmp_seq=7 ttl=64 time=1.720 ms
64 bytes from 192.168.1.1: icmp_seq=8 ttl=64 time=2.102 ms
64 bytes from 192.168.1.1: icmp_seq=9 ttl=64 time=1.481 ms
64 bytes from 192.168.1.1: icmp_seq=10 ttl=64 time=1.829 ms
64 bytes from 192.168.1.1: icmp_seq=11 ttl=64 time=1.679 ms
64 bytes from 192.168.1.1: icmp_seq=12 ttl=64 time=44.561 ms
64 bytes from 192.168.1.1: icmp_seq=13 ttl=64 time=88.844 ms
64 bytes from 192.168.1.1: icmp_seq=14 ttl=64 time=8.853 ms
64 bytes from 192.168.1.1: icmp_seq=15 ttl=64 time=251.638 ms
64 bytes from 192.168.1.1: icmp_seq=16 ttl=64 time=7.148 ms
64 bytes from 192.168.1.1: icmp_seq=17 ttl=64 time=1.748 ms
64 bytes from 192.168.1.1: icmp_seq=18 ttl=64 time=20.817 ms
64 bytes from 192.168.1.1: icmp_seq=19 ttl=64 time=1.407 ms

--- 192.168.1.1 ping statistics ---
20 packets transmitted, 20 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 1.407/51.946/251.638/74.576 ms
```
</details>

<details>
  <summary>No NearDrop, round-trip min/avg/max/stddev = 1.237/1.591/2.055/0.206 ms</summary>
  
```
$ ping -c 20 192.168.1.1
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: icmp_seq=0 ttl=64 time=1.703 ms
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=1.401 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=64 time=1.704 ms
64 bytes from 192.168.1.1: icmp_seq=3 ttl=64 time=1.643 ms
64 bytes from 192.168.1.1: icmp_seq=4 ttl=64 time=1.358 ms
64 bytes from 192.168.1.1: icmp_seq=5 ttl=64 time=1.615 ms
64 bytes from 192.168.1.1: icmp_seq=6 ttl=64 time=1.543 ms
64 bytes from 192.168.1.1: icmp_seq=7 ttl=64 time=1.409 ms
64 bytes from 192.168.1.1: icmp_seq=8 ttl=64 time=1.818 ms
64 bytes from 192.168.1.1: icmp_seq=9 ttl=64 time=1.613 ms
64 bytes from 192.168.1.1: icmp_seq=10 ttl=64 time=1.355 ms
64 bytes from 192.168.1.1: icmp_seq=11 ttl=64 time=2.055 ms
64 bytes from 192.168.1.1: icmp_seq=12 ttl=64 time=1.731 ms
64 bytes from 192.168.1.1: icmp_seq=13 ttl=64 time=1.237 ms
64 bytes from 192.168.1.1: icmp_seq=14 ttl=64 time=1.404 ms
64 bytes from 192.168.1.1: icmp_seq=15 ttl=64 time=1.657 ms
64 bytes from 192.168.1.1: icmp_seq=16 ttl=64 time=1.657 ms
64 bytes from 192.168.1.1: icmp_seq=17 ttl=64 time=1.310 ms
64 bytes from 192.168.1.1: icmp_seq=18 ttl=64 time=1.885 ms
64 bytes from 192.168.1.1: icmp_seq=19 ttl=64 time=1.719 ms

--- 192.168.1.1 ping statistics ---
20 packets transmitted, 20 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 1.237/1.591/2.055/0.206 ms
```
</details>

I suppose it could be caused by wifi scanning. Topic with similar issue https://developer.apple.com/forums/thread/97805

**Comment by macmanjimmy** [comment]
Shhhhhh "Developer" is sensitive

**Comment by grishka** [comment]
> When an Apple STA is coordinating peer-to-peer Wi-Fi work

That's an interesting clue. I just did a packet capture on `awdl0`, the interface for Apple's proprietary P2P Wi-Fi extension, and there *are* some MDNS packets when NearDrop exits and launches. I'm not sure about the specifics of how MDNS works, but maybe there are network configurations when this happens more often. Now I need to find a way to only advertise my MDNS service on specific network interfaces to test this hypothesis 🤔

Also why the hell did I do [this](https://github.com/grishka/NearDrop/blob/7f2fdc43f8c616df73c08d5cac5cfdfc513edcdb/NearbyShare/NearbyConnectionManager.swift#L214)?

> Shhhhhh "Developer" is sensitive

Have you downloaded Xcode yet or are you just going to keep feeling entitled to other people's work for free while being entirely unhelpful?

**Comment by grishka** [comment]
Can you try this build to see whether it fixes anything? [NearDrop.app.zip](https://github.com/grishka/NearDrop/files/12745257/NearDrop.app.zip)

**Comment by unnamed777** [comment]
Looks good.

```
--- 192.168.1.1 ping statistics ---
104 packets transmitted, 104 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 1.275/2.250/8.589/1.240 ms
```

**Comment by grishka** [comment]
@macmanjimmy иди нахуй 😘

**Comment by adrianbj** [comment]
@grishka - looks good here also. Thanks for all your hard work on this - such a useful utility 👍

**Comment by jesuslopezxing** [comment]
> Can you try this build to see whether it fixes anything? [NearDrop.app.zip](https://github.com/grishka/NearDrop/files/12745257/NearDrop.app.zip)

Tested here too and looking good. Thanks!

**Comment by davystrong** [comment]
Tested and seems to work here too. Thanks!

**Comment by leowys** [comment]
Not working for me... I can see my M1 Mac mini from my Samsung phone but nothing appears in my mac after trying to send a file...
