### ISSUE TITLE
Which File to install

### ISSUE THREAD

**Issue by Darug2300** [grishka/NearDrop#6]
Which file do you right click on to install?
The folder is in my Applications folder.

**Comment by rozPierog** [comment]
@Darug2300 
Go to Releases tab on Github https://github.com/grishka/NearDrop/releases/
Download latest ` NearDrop.app.zip`
Follow instructions inside https://github.com/grishka/NearDrop#installation

**Comment by Darug2300** [comment]
Thank you. I downloaded the wrong File. :)
