### ISSUE TITLE
Fail to work on my Mac

### ISSUE THREAD

**Issue by tsurumi-yizhou** [grishka/NearDrop#60]
I'm using the latest version of NearDrop. It was correctly installed and displayed in the bar, but when I tried to transfer files from my phone, tablet and PC (with Nearby Share beta) I couldn't find Mac in list. 

Nowadays it can show menu in system bar, though the entry "Visible to everyone" and "Device name: MacBook Air" both grey and unchangeable. What should I do? Thx.

**Comment by grishka** [comment]
Are you sure your devices are on the same network and your router permits direct connections between them?

**Comment by tsurumi-yizhou** [comment]
Yes, in the same WiFi hotspot.

**Comment by tsurumi-yizhou** [comment]
Oh, I found when I close 5G on my phone, it works!
