### ISSUE TITLE
[Mac OS 12.6.7] App cannot open. Shows a gray "unavailable" icon (circle with a slash) instead of the original app icon.

### ISSUE THREAD

**Issue by DavidBlowi** [grishka/NearDrop#61]

**Comment by modzilla99** [comment]
Works on 12.6.8 for me. You'll probably need to enable notifications in settings

**Comment by leowys** [comment]
Same here, app cannot open. Running MacOs Sonoma Public Beta

**Comment by Darkrayon** [comment]
Same problem for me..Ventura 13.4.1

**Comment by ScrambledBits** [comment]
<img width="259" alt="image" src="https://github.com/grishka/NearDrop/assets/1138771/e68e48a4-3d7f-4c10-8ae8-00b3629009b6">

I cannot go past this, even after clicking "Open Anyway" from Settings -> Privacy & Security

**Comment by grishka** [comment]
Try reading the readme, this might help.
