### ISSUE TITLE
Linux support 

### ISSUE THREAD

**Issue by Aybee5** [grishka/NearDrop#67]
Hi, is there a way to make this work on linux based distro like Ubuntu?

**Comment by grishka** [comment]
No. This is a native macOS app and there currently isn't anything like Wine to run macOS apps on other OSes.

However, there's [a cross-platform Flutter app](https://github.com/PlutoHDDev/CrossDrop) inspired by mine and it does support Linux.

**Comment by Aybee5** [comment]
Thank you for your response.
I will check it out

**Comment by Aybee5** [comment]
Thank you. I'll check it out
