### ISSUE TITLE
Feature request: Homebrew

### ISSUE THREAD

**Issue by trgilmore** [grishka/NearDrop#68]
Any plans to publish to homebrew as a cask?

**Comment by grishka** [comment]
I personally never understood why anyone would want to install non-command-line apps from Homebrew, but I may consider it in the future.

**Comment by Lennix** [comment]
I still everything using homebrew, makes it so much easier. Would love to see this on brew.

**Comment by benwaffle** [comment]
The reason is so that I can update all apps with a single `brew update`

**Comment by brandoningli** [comment]
> I personally never understood why anyone would want to install non-command-line apps from Homebrew, but I may consider it in the future.

I install and manage updates for everything on Linux through a package manager, be it through the CLI or a GUI that interfaces with it, so on the mac I also use, I naturally gravitate towards a package manager like homebrew as my first option.

**Comment by farabf33** [comment]
I strongly advise you to use HomeBrew.
man your app need a distribution system.

**Comment by BingoKingo** [comment]
It's rejected from official tap, visit:
 - https://github.com/Homebrew/homebrew-cask/pull/145241

I've create one in my tap, try `brew install bingokingo/bingokingo/neardrop`

**Comment by grishka** [comment]
Okay then, I didn't know notarization is required to distribute an app through Homebrew. Then it's probably not happening.

**Comment by xela92** [comment]
> I personally never understood why anyone would want to install non-command-line apps from Homebrew, but I may consider it in the future.

Personally I find it nice as I use ansible on my workstation, it's more straight forward instead of making it download a fixed release from github, extract and move to app folder 🙂

**Comment by grishka** [comment]
Ok, go ahead https://github.com/grishka/homebrew-grishka

**Comment by grishka** [comment]
It works 👍
![image](https://github.com/grishka/NearDrop/assets/1478258/21d82208-54ac-4e4f-80d0-728c05444e89)

**Comment by Moulick** [comment]
Haha, I was making a PR but you are way too fast ❤️

**Comment by Moulick** [comment]
not even that, just run `brew bump --open-pr NearDrop` that'll pull the file, make the sha, commit and open PR automatically

**Comment by tenkian4** [comment]
This is not working for me. When I follow the instructions and try and install via `brew install grishka/tap/NearDrop` I get ```==> Downloading https://formulae.brew.sh/api/cask.jws.json

==> Downloading https://formulae.brew.sh/api/formula.jws.json

Warning: No available formula or cask with the name "grishka/grishka/neardrop".```

**Comment by Moulick** [comment]
@tenkian4 the repo was named different from what I wrote originally, `brew install grishka/grishka/neardrop` will work

**Comment by Moulick** [comment]
Opened a PR https://github.com/grishka/NearDrop/pull/94/files to fix the README

**Comment by farabf33** [comment]
> `brew install grishka/grishka/neardrop`

Excelent! it wokrs!
