### ISSUE TITLE
Not showing my Macbook Pro M1

### ISSUE THREAD

**Issue by megaroeny** [grishka/NearDrop#69]
I just installed this app and I have `Everyone` enabled both on my Galaxy Z Fold4 (v13), and my MacBook Pro M1 Airdrop settings. My phone doesn't show my MacBook, even after restarting. This must be a bug with the app, right?

**Comment by grishka** [comment]
Are both devices on the same wifi network?

**Comment by megaroeny** [comment]
> Are both devices on the same wifi network?

Yeah they are. I'm on a public network at a coffee shop and confirmed they were. I had a VPN but even disabling it on my MacBook didn't help.

I'll try at my home network soon.

**Comment by grishka** [comment]
> I'm on a public network at a coffee shop and confirmed they were.

Yeah, that may be the problem. Public networks are often set up to isolate connected devices from each other (for good reason).

**Comment by megaroeny** [comment]
Got it working at home, thanks!
