### ISSUE TITLE
[Question] How can I debug errors in NearDrop?

### ISSUE THREAD

**Issue by raishish** [grishka/NearDrop#71]
I want to debug the following error encountered when sending a file from android phone to NearDrop on a mac:

`Failed to receive files from phone. This operation couldn't be completed. (SwiftProtobuf.BinaryDecodingError Error)`

I see that this could be due to any of the problems mentioned in this switchcase: https://github.com/apple/swift-protobuf/blob/main/Sources/SwiftProtobuf/BinaryDecodingError.swift, so wanted to debug and file the correct issue.

If I can get access to a console where I can dig deeper into the code or a debug build, that would be great.

Thanks!

**Comment by grishka** [comment]
You have two options:

1. Run NearDrop from the terminal (`/Applications/NearDrop.app/Contents/MacOS/NearDrop`) to see its logging output
2. Clone the repo, open the project in Xcode, then build and run it from there
