### ISSUE TITLE
App can’t be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by emmaakachukwu** [grishka/NearDrop#72]
I downloaded the [latest release](https://github.com/grishka/NearDrop/releases/tag/v1.1.1) - `v1.1.1` and unzipped it. On opening the app, I get the message
```
“NearDrop” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.
```

See screenshot below
<img width="294" alt="Screenshot 2023-09-10 at 3 14 16 AM" src="https://github.com/grishka/NearDrop/assets/43121616/0ff5a65b-e67c-43b7-9d9e-f6d403bbe6c0">

I'm currently on MacOS Ventura `v13.5.1` (Apple M2 Pro chip)

**Comment by grishka** [comment]
You have to right-click it and select "open". See the readme.
