### ISSUE TITLE
share links? 

### ISSUE THREAD

**Issue by codeagencybe** [grishka/NearDrop#73]
Hello

I tried your app today first time and it didn't work for browser links? 
I tested with a simple image file and pdf file and that works fine, but why no links? 

After I try to share a browser link from my Android to my MacOs, Neardrop just return an error after I click accept on MacOs and then just crashes and close app and nothing happens. 

I was expecting it would trigger my Mac to accept the link and open it in default MacOs browser? 

Secondary, is there an option to disable the "accept" step each time for every single share on MacOs? 
Once I paired, I would like to "remember" that my device is OK to keep sending more. 
I often start browser sessions on my Mobile and then handover to my Mac. 
It gets a bit annoying if I have to keep accepting 30+ clicks every time.

**Comment by grishka** [comment]
Links are currently not supported.

Remembering devices is also not supported because I haven't found a reliable non-hacky way to identify them.
