### ISSUE TITLE
Can not share URL just like the screenshots

### ISSUE THREAD

**Issue by KoukeNeko** [grishka/NearDrop#8]
<img width="378" alt="Screenshot 2023-04-14 at 2 37 44 PM" src="https://user-images.githubusercontent.com/111033412/231962865-5e333960-7ce1-42c1-af6c-1ea7863b67af.png">

<img width="372" alt="Screenshot 2023-04-14 at 2 37 35 PM" src="https://user-images.githubusercontent.com/111033412/231962966-c1ff8620-6b95-47ee-8227-6972a580272b.png">

![Screenshot_20230414-142918](https://user-images.githubusercontent.com/111033412/231963244-6e33b3da-951b-4c58-b27b-8426e01dd105.png)

**Comment by Darug2300** [comment]
So far my Galaxy can see my Macbook, and has a pin with 4 characters. The Neardrop icon is up the top, but the 2 options are greyed out?

**Comment by Techno-Source2022** [comment]
When I share the browser URL from my Galaxy crome to my MacBook it crashes the same way.
It's a great tool, please improve it for an even better product!

**Comment by PlutoHDDev** [comment]
Duplicate #3 and #16

**Comment by venelinn** [comment]
Guys, why don't you use Chrome build in share "Send to your devices"?
![Screenshot_20230417-153531](https://user-images.githubusercontent.com/2440014/232592563-f2c22824-75f3-48d1-89e4-05b65d3facf1.png)

**Comment by Moulick** [comment]
@venelinn Sharing URLs is not an issue limited to Chrome, maybe I might be using a different browser or a different app needs to share any xyz text.

**Comment by 6thday** [comment]
same error when i try to send file from android 13 to 13.4.1c m1
