### ISSUE TITLE
Unable to share file from Mac

### ISSUE THREAD

**Issue by nezorflame** [grishka/NearDrop#90]
Hi!
Stable macOS Sonoma, release 2.0.

I don't see an option to share the file from Mac (there's no option for NearDrop).
"Edit Extensions" option also doesn't list it.
I've attached screenshots showing this.

<img width="250" alt="image" src="https://github.com/grishka/NearDrop/assets/3906766/4e8dfe18-8d58-42d6-850b-b268032cfcce">

<img width="250" alt="image" src="https://github.com/grishka/NearDrop/assets/3906766/4447a434-bae9-4ed4-ba04-426ea82fb34c">

<img width="250" alt="image" src="https://github.com/grishka/NearDrop/assets/3906766/161f0404-fa27-4b45-8656-22d7b3295f40">

**Comment by eliasacab** [comment]
Came here for the same reason, but just found the solution:

Go to System Settings > Privacy & Security > Extensions (bottom) > Sharing > and check NearDrop at the bottom.

Can't get it show my Android phone though, even though I have Nearby set to visible to everyone, only the Mac itself shows.

**Comment by eliasacab** [comment]
Oh that did it! Google Files > Nearby Share > Receive. Now my phone shows up and I can receive files from Mac. Thanks!! Appreciate your work on this.

**Comment by nezorflame** [comment]
@grishka ye, enabling the Extension helped.
But I also don't see my phone in the menu, only the Mac itself, and I have enabled receiving files from the Files app.

**Comment by anuragdeshpande** [comment]
> Oh that did it! Google Files > Nearby Share > Receive. Now my phone shows up and I can receive files from Mac. Thanks!! Appreciate your work on this.

Thank you. Appreciate all the work. This is a very handy app and I love it! v2 is just breaking the ceiling once again.

**Comment by grishka** [comment]
2.0.1 fixes this by ignoring an MDNS service if its network interfaces include the loopback interface. There is actually supposed to be a text that tells you to open Google Files, but no one has seen it yet ¯\_(ツ)_/¯

Don't update to 2.0.1 if you find it more convenient to send files to yourself rather than manually copying them to your downloads folder.
