### ISSUE TITLE
No NearDrop option in sharing menu on Mac

### ISSUE THREAD

**Issue by ADaniyalov** [grishka/NearDrop#96]
I've used previous version of the app, but read news about new update. I didn't manage to find a native update way, so I've downloaded 2.0.2 version and installed. Unfortunatelly, I can't find NearDrop neither in sharing menu, nor in extensions. 
<img width="230" alt="image" src="https://github.com/grishka/NearDrop/assets/48780529/e9c98833-8cc2-4590-9e81-776f3ca80abd">
<img width="415" alt="image" src="https://github.com/grishka/NearDrop/assets/48780529/07adea14-d0b6-4054-b9f3-b3b622570b89">
I use MBP 14 M1 Pro, Sonoma.

**Comment by grishka** [comment]
Restarting Finder might help. At least it did for me while debugging.

**Comment by ADaniyalov** [comment]
Helped, Thanks. 

BTW, great app! 
It can only be improved, if I could use it without opening goggle files to receive, but I'm not sure, if it's something you can do or device company only can.

**Comment by grishka** [comment]
> if I could use it without opening goggle files to receive

There's no API to send the correct BLE broadcasts. I tried: #91

**Comment by harpratap** [comment]
I am on macOS 12.6.7 on Macbook Pro 2019 and I cannot see any option to share using NearDrop when I select `Share > ` option in the menu

**Comment by grishka** [comment]
Did you try restarting Finder? Right-click it in the dock to see the restart option

**Comment by harpratap** [comment]
Yes, I did a relaunch too, I still don't see any option in dropdown or in the "others" setting

**Comment by mikezamayias** [comment]
@grishka I've also tried restarting Finder, rebooting, quitting and reopening the app, but NearDrop never appears in the Share menu. If it helps I'm on macOS 14.0 (23A344). I'm also not seeing NearDrop in the System Settings (or System Preferences) app for Finder Extensions (Right Click a file in Finder -> Share... -> Edit Extensions...)

**Comment by jrvgr** [comment]
I needed to have the receive tab open on my phone and then i could add the share menu item

**Comment by kokroo** [comment]
@ADaniyalov Can you please reopen this issue? The fixes mentioned here are not working.
@grishka Thanks for making this software! I am also running a Macbook 14 M1 Pro on Sonoma, and I cannot see neardrop on the share menu despite the fixes mentioned above.

**Comment by dbodyas** [comment]
Finally I was able to add it to share menu. I don't know what exactly make it happen but here is my steps:

- reboot MacOS
- enable Device visibility in Android Settings -> Nearby Share
- open android `Files` app -> `Nearby Share` tab -> `Receive` button
- open this NearDrop app
- open mac settings app -> Share menu -> add item to list (have to open it manually, not from Finder menu)
